#ifndef __ERRTMR_H
#define __ERRTMR_H

#include "module.h"

enum {
    ERROR_TIMER_ALLOC_INVHANDLE = ERROR_BEGIN (MODULE_TIMER),
    ERROR_TIMER_ALLOC_INVCB,
    ERROR_TIMER_ALLOC_NOTIMER,
    ERROR_TIMER_FREE_INVHANDLE,
    ERROR_TIMER_START_INVHANDLE,
    ERROR_TIMER_START_INVSTATE,
    ERROR_TIMER_RESTART_INVHANDLE,
    ERROR_TIMER_RESTART_INVSTATE,
    ERROR_TIMER_STOP_INVHANDLE,
    ERROR_TIMER_STOP_INVSTATE,
    ERROR_TIMER_STATE_INVSTATE
};

#endif

