#ifndef __ERRHEAP_H
#define __ERRHEAP_H

#include "module.h"

enum {
    ERROR_HEAP_INIT_INVADDR = ERROR_BEGIN (MODULE_HEAP),
    ERROR_HEAP_INIT_INVALIGN,
    ERROR_HEAP_ALLOC_NOTINIT,
    ERROR_HEAP_ALLOC_INVSIZE,
    ERROR_HEAP_ALLOC_INVLOC,
    ERROR_HEAP_ALLOC_NOMEM1,
    ERROR_HEAP_ALLOC_NOMEM2,
    ERROR_HEAP_ALLOC_INVCONTEXT,
    ERROR_HEAP_FREE_NOTINIT,
    ERROR_HEAP_FREE_INVSIZE,
    ERROR_HEAP_FREE_INVBUF,
    ERROR_HEAP_FREE_INVMBLOCK1,
    ERROR_HEAP_FREE_INVMBLOCK2,
    ERROR_HEAP_FREE_INVMBLOCK3,
    ERROR_HEAP_FREE_INVMHEAD,
    ERROR_HEAP_FREE_INVMTAIL
};

#endif

